/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2022-02-28 02:32:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/Project/Spring/laptopregapp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/laptopregapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/Project/Spring/laptopregapp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/laptopregapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1615341766491L));
    _jspx_dependants.put("jar:file:/D:/Project/Spring/laptopregapp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/laptopregapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<script src=\"/js/jquery.autocomplete.min.js\"></script>\r\n");
      out.write("<script src=\"/js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link href=\"/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"/css/signin.css\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"canonical\" href=\"https://getbootstrap.com/docs/5.0/examples/sign-in/\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/jquery-ui.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/css/ui.jqgrid.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/js/i18n/grid.locale-kr.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"/js/jquery.jqGrid.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\tjQuery.browser = {};\r\n");
      out.write("\t(function() {\r\n");
      out.write("\t\tjQuery.browser.msie = false;\r\n");
      out.write("\t\tjQuery.browser.version = 0;\r\n");
      out.write("\t\tif (navigator.userAgent.match(/MSIE ([0-9]+)\\./)) {\r\n");
      out.write("\t\t\tjQuery.browser.msie = true;\r\n");
      out.write("\t\t\tjQuery.browser.version = RegExp.$1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})();\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"Mark Otto, Jacob Thornton, and Bootstrap contributors\">\r\n");
      out.write("<meta name=\"generator\" content=\"Hugo 0.84.0\">\r\n");
      out.write("<title>Signin Template · Bootstrap v5.0</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap core CSS -->\r\n");
      out.write("<style>\r\n");
      out.write(".bd-placeholder-img {\r\n");
      out.write("\tfont-size: 1.125rem;\r\n");
      out.write("\ttext-anchor: middle;\r\n");
      out.write("\t-webkit-user-select: none;\r\n");
      out.write("\t-moz-user-select: none;\r\n");
      out.write("\tuser-select: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( min-width : 768px) {\r\n");
      out.write("\t.bd-placeholder-img-lg {\r\n");
      out.write("\t\tfont-size: 3.5rem;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-jqgrid {\r\n");
      out.write("\tmargin-left: auto;\r\n");
      out.write("\tmargin-right: auto;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-jqgrid.ui-widget.ui-widget-content.ui-corner-all {\r\n");
      out.write("\twidth: 100% !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-jqgrid-view {\r\n");
      out.write("\twidth: 100% !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-jqgrid-hdiv {\r\n");
      out.write("\twidth: 100% !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-jqgrid .ui-jqgrid-hbox {\r\n");
      out.write("\twidth: 100% !important;\r\n");
      out.write("\tpadding: 0 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-jqgrid-htable {\r\n");
      out.write("\twidth: 100% !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-jqgrid-bdiv {\r\n");
      out.write("\twidth: 100% !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-jqgrid-btable {\r\n");
      out.write("\twidth: 100% !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".ui-jqgrid-pager {\r\n");
      out.write("\twidth: 100% !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".div-label {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tdisplay: inline-flex;\r\n");
      out.write("\tmargin: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-signin {\r\n");
      out.write("\twidth: 600px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input-label {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- Custom styles for this template -->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body class=\"text-center\">\r\n");
      out.write("\t<main class=\"form-signin\"> <img class=\"mb-4\" src=\"/image/kd.png\" alt=\"\" width=\"72\" height=\"57\">\r\n");
      out.write("\t<h1 class=\"h3 mb-3 fw-normal\">\r\n");
      out.write("\t\t재택근무 노트북 </br> 등록 페이지\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<form method=\"post\" action=\"/registerCamera.do\" name=\"registerForm\" id=\"registerForm\">\r\n");
      out.write("\t\t\t\t<button class=\"w-100 btn btn-lg btn-primary\" style=\"width: 100px; height:100px; margin-top: 10px;\" type=\"button\" id=\"registerBtn\"><b style=\"font-size:30px;\">등록(수령)</b></button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<form method=\"post\" action=\"/returnCamera.do\" name=\"returnForm\" id=\"returnForm\">\r\n");
      out.write("\t\t\t\t<button class=\"w-100 btn btn-lg btn-success\" style=\"width: 100px; height:100px; margin-top: 10px;\" type=\"button\" id=\"returnBtn\"><b style=\"font-size:30px;\">반납</b></button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("<!-- \t\t\t<form method=\"post\" action=\"/returnPageManual.do\" name=\"manualreturnForm\" id=\"manualreturnForm\">\r\n");
      out.write("\t\t\t\t<button class=\"w-100 btn btn-lg btn-secondary\" style=\"width: 100px; margin-top: 10px;\" type=\"button\" id=\"manualreturnBtn\">Manual Return</button>\r\n");
      out.write("\t\t\t</form> -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<p class=\"mt-5 mb-3 text-muted\">&copy; Since Corona Virus, 2019–2022</p>\r\n");
      out.write("\t</main>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(\"#registerBtn\").on(\"click\", function(e) {\r\n");
      out.write("\t\t$(\"#registerForm\").submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#returnBtn\").on(\"click\", function(e) {\r\n");
      out.write("\t\t$(\"#returnForm\").submit();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("/* \t$(\"#manualreturnBtn\").on(\"click\", function(e) {\r\n");
      out.write("\t\t$(\"#manualreturnForm\").submit();\r\n");
      out.write("\t}); */\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
